# â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”“
# â”ƒ ðŸ“œ pubspec.yaml - GrimÃ³rio dos Instrumentos MÃ¡gicos â”ƒ
# â”—â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”›

name: instrumentos_magicos
description: Artefatos consagrados utilizados por DrEstranho em conjuraÃ§Ãµes extraplanares
version: 1.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.3.0
  path: ^1.8.3
  yaml: ^3.1.2

executables:
  rituais: bin/rituais.dart
